### ISSUE TITLE
Update to more recent versions of awkward/uproot

### ISSUE THREAD

**Issue by mcremone** [LPC-DM/decaf#19]
@jpivarski we would need to update to more modern versions of awkward/uproot. At the moment we are using:

pip install --user uproot==3.3.2
pip install --user --upgrade uproot-methods==0.3.3
pip install --user awkward==0.7.1

More recent versions were breaking some of the calculations we are performing in our analysis code, but at the best of my remembering these were discussed and fixed.

Also, we would like to discuss about the possibility to avoid some workarounds we are currently using to make things work. As an example:

- Exceptions when a branch is not find in the input root file: https://github.com/LPC-DM/decaf/blob/master/grinder/analysis/darkhiggs.py#L78-L81
- Explicitly check the size of the content array: https://github.com/LPC-DM/decaf/blob/master/grinder/analysis/darkhiggs.py#L299-L302
- Extensive use of reducers (.sum()) to "fill the holes" and ensure arrays are of the same length: https://github.com/LPC-DM/decaf/blob/master/grinder/analysis/darkhiggs.py#L372

**Comment by areinsvo** [comment]
This has been resolved with the latest commit and updates to fnal-column-analysis-tools. Closing for now.
